<?php
// Optional overrides for lp-bootstrap.php. Return an array to override defaults.
return [
    // Legacy single-instance aliases.
    // 'root_dir' => '/absolute/path/to/project/root',
    // 'base_url' => '/lawndingpage',
    // 'public_dir' => '/absolute/path/to/public',
    // 'admin_dir' => '/absolute/path/to/admin',
    // 'data_dir' => '/absolute/path/to/data/public/res/data',
    // 'img_dir' => '/absolute/path/to/data/public/res/img',
    // 'users_path' => '/absolute/path/to/data/admin/users.json',
    // New path keys for shared-core / instance-aware layouts.
    // 'core_root_dir' => '/absolute/path/to/core/root',
    // 'core_public_dir' => '/absolute/path/to/core/public',
    // 'core_admin_dir' => '/absolute/path/to/core/admin',
    // 'instance_root_dir' => '/absolute/path/to/instance/root',
    // 'instance_public_dir' => '/absolute/path/to/instance/public',
    // 'instance_admin_dir' => '/absolute/path/to/instance/admin',
    // 'instance_data_dir' => '/absolute/path/to/instance/data/public/res/data',
    // 'instance_img_dir' => '/absolute/path/to/instance/data/public/res/img',
    // 'instance_private_dir' => '/absolute/path/to/instance/data',
    // 'instance_runtime_admin_dir' => '/absolute/path/to/instance/data/admin',
    // 'instance_logs_dir' => '/absolute/path/to/instance/data/logs',
    // 'instance_state_dir' => '/absolute/path/to/instance/data/state',
    // 'instance_modules_dir' => '/absolute/path/to/instance/modules',
    // 'instance_config_path' => '/absolute/path/to/instance/lp-instance.php',
    // 'core_overrides_path' => '/absolute/path/to/core/lp-core-overrides.php',
    // 'errors_path' => '/absolute/path/to/instance/data/logs/errors.txt',
    // 'tg_bot_path' => '/absolute/path/to/instance/data/admin/lp-tgBot.json',
    // 'tg_membership_cache_path' => '/absolute/path/to/instance/data/admin/lp-tgMembershipCache.json',
    // 'initialized_flag_path' => '/absolute/path/to/instance/data/state/.lawndingpage-initialized',
    // 'session_cookie_name' => 'lp_demo',
    // 'session_cookie_path' => '/',
    // 'session_cookie_domain' => '.lawnding.page',
    // 'session_cookie_secure' => false,
    // 'session_cookie_httponly' => true,
    // 'session_cookie_samesite' => 'Strict',
];
